[package]
name = "rust_amqp_demo"
version = "0.1.0"
authors = ["Greg Baker <ggbaker@sfu.ca>"]
edition = "2018"

[dependencies]
lapin = "~1.7"
futures-util = "~0.3"
async-global-executor = "~2.0"
serde = "~1.0"
serde_json = "~1.0"
uuid = { version = "~0.8", features = ["v4"] }
